import "@/style/globals.css";

import type { Metadata } from "next";
import { TRPCReactProvider } from "@/lib/trpc/client";

export const metadata: Metadata = {
  title: "full-stack-template-nextjs",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
