import "@/style/globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "full-stack-template-nextjs",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body>{children}</body>
    </html>
  );
}
